server:
  port: 8087
  servlet:
    context-path: /
tomcat:
  remote-ip-header: x-forward-for
  uri-encoding: UTF-8
  max-threads: 10
  background-processor-delay: 30
  basedir: ${user.home}/tomcat/

jasypt:
  encryptor:
    password: HT95279527

spring:
  application:
    name: sync-el
  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true
  datasource:
    driver-class-name: com.xugu.cloudjdbc.Driver
    url: jdbc:xugu://10.20.64.167:5138/BABJ_SMDB?ips=10.20.64.168,10.20.64.169&recv_mode=0&char_set=utf8&compatibleoracle=false
    username: USR_SOD
    password: Pnmic_qwe123
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
      initialSize: 1
      minIdle: 3
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      # minEvictableIdleTimeMillis: 30000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false

mybatis:
  type-aliases-package: com.piesat.*.entity
  mapper-locations: classpath:mapper/*.xml
  callSettersOnNulls: true
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
ei:
  eiUrl: http://127.0.0.1:29999/transfer
